# Generated by Django 4.2.4 on 2023-08-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='borrowed_books',
            field=models.ManyToManyField(default=None, related_name='borrowed_by', to='books.book'),
        ),
    ]
